# Generated by Django 3.0.3 on 2020-08-02 11:29

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZipUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_file', models.FileField(storage=django.core.files.storage.FileSystemStorage(), upload_to='gallery-zip-files/')),
                ('title', models.CharField(blank=True, help_text='All uploaded photos will be given a title made up of this title + a sequential number.<br>This field is required if creating a new gallery, but is optional when adding to an existing gallery - if not supplied, the photo titles will be creating from the existing gallery name.', max_length=255, null=True)),
                ('caption', models.TextField(blank=True, help_text='Caption will be added to all photos.', null=True)),
                ('description', models.TextField(blank=True, help_text='A description of this Gallery. Only required for new galleries.', null=True)),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck this to make the uploaded gallery and included photographs private.')),
                ('gallery', models.ForeignKey(blank=True, help_text='Select a gallery to add these images to. Leave this empty to create a new gallery from the supplied title.', null=True, on_delete=django.db.models.deletion.CASCADE, to='photologue.Gallery')),
            ],
        ),
    ]
