# Generated by Django 4.2.3 on 2023-07-28 18:39

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_alter_photo_effect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watermark',
            name='image',
            field=models.ImageField(upload_to=pathlib.PurePosixPath('photologue/watermarks'), verbose_name='image'),
        ),
    ]
